# Generated by Django 3.2.8 on 2021-11-05 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211104_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='bid_price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='user',
        ),
        migrations.AddField(
            model_name='listings',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Toy', 'Toy'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Travel', 'Travel'), ('other', 'other')], max_length=30),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_comment', to='auctions.listings')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.listings')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_bid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
