# Generated by Django 3.2.8 on 2021-11-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='owner',
            field=models.CharField(default='abduallah', max_length=64),
            preserve_default=False,
        ),
    ]
